'use client';
import {useRef,useState} from 'react';
import type {PointerEvent as PE} from 'react';
export const stampPhotos=['puppy-05.jpg','puppy-06.jpg','puppy-07.jpg','puppy-08.jpg'];
export function Stamp({kind=0}:{kind?:number}){return <span className={'birthday-stamp stamp-color-'+kind}><img src={'/images/'+stampPhotos[kind]} alt="幼犬邮票"/><b>{'生日快乐'[kind]}</b></span>;}
export function StampBoard({onDone,onStart,onSound}:{onDone:(id:string)=>void;onStart:()=>void;onSound:()=>void}){
 const [placed,setPlaced]=useState<(number|null)[]>([null,null,null,null]),[active,setActive]=useState<number|null>(null),[delta,setDelta]=useState([0,0]);
 const slots=useRef<(HTMLDivElement|null)[]>([]),drag=useRef<{n:number;x:number;y:number;pointer:number}|null>(null);
 const place=(n:number,slot:number)=>{if(placed.includes(n)||placed[slot]!==null||slot!==n)return;setPlaced(p=>p.map((v,i)=>i===slot?n:v));onSound();onDone('stamp-'+n);};
 const down=(e:PE<HTMLButtonElement>,n:number)=>{if(drag.current||placed.includes(n))return;onStart();e.currentTarget.setPointerCapture(e.pointerId);drag.current={n,x:e.clientX,y:e.clientY,pointer:e.pointerId};setActive(n);setDelta([0,0]);};
 const up=(e:PE<HTMLButtonElement>)=>{const d=drag.current;if(!d||d.pointer!==e.pointerId)return;const slot=slots.current.findIndex((el,i)=>{if(!el||placed[i]!==null||i!==d.n)return false;const r=el.getBoundingClientRect();return e.clientX>=r.left-20&&e.clientX<=r.right+20&&e.clientY>=r.top-20&&e.clientY<=r.bottom+20;});if(slot>=0)place(d.n,slot);drag.current=null;setActive(null);setDelta([0,0]);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);};
 return <div className="stamp-workspace"><div className="postcard-paper"><div className="stamp-destinations">{placed.map((n,i)=><div key={i} className={'stamp-destination letter-envelope envelope-'+i+(n!==null?' occupied':'')} ref={el=>{slots.current[i]=el;}}><span className="envelope-fold"/><span className="letter-address"><i/><i/><i/></span>{n!==null?<span className="newly-placed"><Stamp kind={n}/></span>:<i/>}</div>)}</div></div><div className="stamp-tray">{[2,0,3,1].map(n=><button key={n} disabled={placed.includes(n)} className={'tray-stamp'+(active===n?' in-hand':'')+(placed.includes(n)?' used':'')} style={{transform:active===n?'translate('+delta[0]+'px,'+delta[1]+'px) rotate(-4deg)':undefined}} aria-label={'把第'+(n+1)+'张生日邮票贴到上方空位'} onPointerDown={e=>down(e,n)} onPointerMove={e=>{const d=drag.current;if(d&&d.pointer===e.pointerId)setDelta([e.clientX-d.x,e.clientY-d.y]);}} onPointerUp={up} onPointerCancel={()=>{drag.current=null;setActive(null);setDelta([0,0]);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onStart();place(n,n);}}}><Stamp kind={n}/></button>)}</div></div>;
}
